version: "3.9"
  services:
    springapp:
      build: .
      container_name: springapp
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      ports:
        - 80:80
      restart: always
      depends_on:
        - db
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_USER=usr
        - POSTGRES_PASSWORD=pwd
        - POSTGRES_DB=demoDB
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5430:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always
  volumes:
    pgdata: